name: deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install and Build
        run: |
          npm ci
          npm run build

      - name: Copy dist to portfolio folder and Deploy
        run: |
          echo "Copying dist to /home/shenkz/portfolio"
          rsync -a --delete./dist/ /home/shenkz/portfolio/dist/

          echo "Copying docker files"
          cp docker-compose.yml nginx.conf /home/shenkz/portfolio/

          echo "Restarting Containers"
          cd /home/shenkz/portfolio
          docker compose up -d --build --no-deps portfolio
          docker compose ps