name: deploy

on:
  push:
    branches: [main]
jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    steps:
     - name: checkout
       uses: actions/checkout@v4
       with:
         path: /home/shenkz/porfolio

     - name: Build and Restart porfolio
       working-directory: /home/shenkz/porfolio
       run: |
         echo "Pulling latest code"
         git pull
         echo "Building docker image"
         docker compose -f docker-compose.yml build --no-cache
         echo "Restarting Containers"
         docker compose -f docker-compose.yml up -d
         docker compose ps
         echo "Deployment finished successfully!"
         
        