name: deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install and Build
        run: |
          npm ci
          npm run build
          
      - name: Deploy to /opt/portfolio
        run: |
          set -e # stop on first error
          
          echo "1. Copying dist"
          sudo rm -rf /opt/portfolio/dist
          sudo mkdir -p /opt/portfolio/dist
          sudo cp -r ./dist/* /opt/portfolio/dist/

          echo "2. Copying docker files"
          sudo cp /home/shenkz/portfolio/docker-compose.yml /home/shenkz/portfolio/nginx.conf /opt/portfolio/

          echo "3. Restarting Containers"
          cd /opt/portfolio
          docker compose config # this will validate service name first
          docker compose up -d --build portfolio
          docker compose ps